### ISSUE TITLE
Error when logging in: /home/username/.kre/kvm.sh: Syntax error: "(" unexpected (expecting ";;")

### ISSUE THREAD

**Issue by wilfriedb** [aspnet/dotnetsdk#114]
Last week I installed aspnet on Linux Mint 17.1 and since then when trying to log in the system logs me out again immediately with the error message: 
/home/username/.kre/kvm/kvm.sh: Syntax error: "(" unexpected (expecting ";;")
I had to start in recovery mode, log in as root, mount the file system rw and rename the file to be able to log in again.
Running at the terminal:
sh kvm.sh 
gives: 
kvm.sh: 354: kvm.sh: Syntax error: "(" unexpected (expecting ";;")
At line 354 is the text 
local arr=()
Does anyone know what the problem is here?

**Comment by arthur-peka** [comment]
Well it means that kvm is not usable out of the box on Debian-like systems. Maybe symlink creation should be part of that one-line install script?

**Comment by Scalpel78** [comment]
This issue should be reopened. This just happened to me when installing on Linux Mint as well. After installation I am no longer able to log into Linux. That is a MAJOR problem. That is just about as bad as it can get - not only doesn't dnvm/kvm work, but the server becomes unusable for that user.

**Comment by Scalpel78** [comment]
See issue #222 for workaround.

**Comment by arthur-peka** [comment]
@Scalpel78 I guess we should open a new issue about this (duplicate). Noone gives a **** about some discussion in closed issue, it seems :)
