### ISSUE TITLE
Build command in mac won't find KoreBuild

### ISSUE THREAD

**Issue by rlbisbe** [aspnet/dotnetsdk#17]
Enviromnent:

OSX 10.9.3 
Xamarin Studio 5.1.1
Mono 4.6.0 Runtime

The trace is the following:

Unable to find package 'KoreBuild'.
Installing 'Sake 0.2'.
Successfully installed 'Sake 0.2'.
info: Target default
info: Target pre-clean
info: Target clean
info: Target post-clean
info: Target validate
info: Target initialize
info: Target copy-kvm
info: Copying .DS_Store
info: Copying kvm.cmd
info: Copying kvm.ps1
info: Copying kvm.sh
info: Copying kvmsetup.cmd
info: Updating /Users/robertoluis/kvm/artifacts/kvm.ps1
info: Updating /Users/robertoluis/kvm/artifacts/kvm.sh
info: Target compile
info: Target test-compile
info: Target test
info: Target package-prepare
info: Target package

**Comment by rhires** [comment]
@davidfowl What was the fix for this? I'm having the same issue.

**Comment by rburkhal** [comment]
Same here.

Unable to find package 'KoreBuild'.
