### ISSUE TITLE
failing nuget package restore with unreachable server

### ISSUE THREAD

**Issue by vermegi** [aspnet/dotnetsdk#171]
In my package sources I have an additional package source listed, which is unreachable once not connected to the corporate network. I also have the official nuget package source listed. Once I open a solution, it will try and restore my nuget packages, but it fails doing this, since it keeps on complaining about the unreachable corporate network server. As a result of this any Bower packages will fail to restore as well.

Unchecking the unreachable server in my nuget package sources solves the problem.

**Comment by davidfowl** [comment]
This is the wrong repository. File this on aspnet/Home with the full error messages captured.
