### ISSUE TITLE
Can dnvm use local feed?

### ISSUE THREAD

**Issue by llorchCN** [aspnet/dotnetsdk#496]
dnvm always fails when install new dnx. How can use a local feed before(instead of) the dnvm_default_feed?

**Comment by muratg** [comment]
Doesn't it work when you set the environment variable?

**Comment by llorchCN** [comment]
It works but not so good. What about dnvm searches local cache first and then use default feed?

**Comment by johandanforth** [comment]
+1

**Comment by muratg** [comment]
DNVM/DNX/DNU are being retired in the next release in favor of dotnet CLI.

**Comment by johandanforth** [comment]
Yep. I've come pretty far in setting up a local dotnet core feed now :)
