### ISSUE TITLE
Tab-Complete

### ISSUE THREAD

**Issue by jchannon** [aspnet/dotnetsdk#498]
Do you know of any efforts underway to make tab-complete for dnvm/dnx/dbu etc possible in zsh/bash/powershell.  For example you type `dnvm ins + TAB` and it completes to `dnvm install`

**Comment by muratg** [comment]
For RC2, we're planning to retire dnvm, dnx and dnu in favor of dotnet CLI.  I recommend filing a bug in dotnet/CLI repo.

**Comment by jchannon** [comment]
It is see linked issue above
