### ISSUE TITLE
Access to the path 'C:\Users\{%USERPROFILE%}\.dnx\runtimes\temp\' is denied

### ISSUE THREAD

**Issue by EugeneTe** [aspnet/dotnetsdk#499]
The similar issue was already closed on Windows 7.

I have this problem on Windows 10 when I try to install dnx-clr-win-x86.1.0.0-rc1-update1.

.NET Version Manager v1.0.0-rc2-15546

I am running powershell as Administrator and all users including Administrator got Full Control on that temp folder.

Could you look into this?

Thanks,
Eugene

**Comment by EugeneTe** [comment]
It looks like McAfee issue

**Comment by dhanuka777** [comment]
@Eugene can you explain a solution for this please? Should a user disable McAfee. I had to uninstall McAfee.
