### ISSUE TITLE
Path with & is not processed correctly even when wrapped in " "

### ISSUE THREAD

**Issue by AndrewH2O** [aspnet/dotnetsdk#500]
dnvm commands that amend the environment path on windows 8.1 report 'MySQL' is not recognised as an internal or external command where the path contains an &, even though the path is surrounded by quotes:

eg Path contains:  "C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\";"C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\Doctrine extensions for PHP\"

dnvm use 1.0.0-rc1-update1 -r clr -arch x64
Adding C:\Users[myUserName].dnx\runtimes\dnx-clr-win-x64.1.0.0-rc1-update1\bi
n to process PATH
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'MySQL' is not recognized as an internal or external command,
operable program or batch file.

Note:
what is happening here I think is that
"C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\"
is split out as two : 
C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4
MySQL Utilities 1.5.4 1.5\
where MySql is seen as a separate instruction
and similarly for "C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\Doctrine extensions for PHP\"
Which explains why the error above is seen twice.
At first I thought that MySql/bin needed to be added to the path but that is not the issue here.

Workaround:
temporarily amend path to exclude '&' under environment variables.

**Comment by muratg** [comment]
Thanks for reporting this issue.  For RC2, we're planning to retire dnvm, dnx and dnu in favor of dotnet CLI.  Moving this to backlog until the transition.
