### ISSUE TITLE
Is "dnvm use latest" supposed to work?

### ISSUE THREAD

**Issue by simonech** [aspnet/dotnetsdk#506]
I can do `dnvm install latest`, but would be nice to be able to specify that I want to use the latest version of DNX, just changing runtime flavour.
Now if I do `dnvm use -r coreclr` I get asked for VersionOrAlias: would be nice that if I don't specify the version it just keeps the same version, just changing arch or runtime.

**Comment by muratg** [comment]
DNVM/DNX/DNU are being retired in RC2, so no more work is planned.

**Comment by replete** [comment]
I appreciate that everything is changing between RC1 and RC2, but how can I actually install a dev runtime? I have no idea.

**Comment by muratg** [comment]
@replete Please watch https://github.com/dotnet/cli repo for issues around this.  Instructions and links for  installers can be found on https://dotnet.github.io.

**Comment by simonech** [comment]
Maybe this should be closed?
