### ISSUE TITLE
breaks with user folder that contains a space

### ISSUE THREAD

**Issue by markentingh** [aspnet/dotnetsdk#510]
If I try using my first & last name as a Windows User account name, then the c:\users\ folder contains a space, thus making DNVM break when trying to run a web app in Visual Studio.

Specifically, when trying to load the Microsoft.Data.SqlClient reference while running DNX from Visual Studio, it breaks. If I try running dnx web from command line, it works, but not in Visual Studio. I found out that this is caused because of the space in the user folder.

**Comment by muratg** [comment]
@markentingh What version of DNVM?  This should have been fixed.  Does your dnvm.cmd contain the change in https://github.com/aspnet/dnvm/pull/224/files?

**Comment by markentingh** [comment]
I downloaded the latest version of Visual Studio 2015 Express yesterday right after formatting & installing Windows 7 Professional on my laptop. I was using 1.0.0-rc1-final x64 CoreCLR

**Comment by BrennanConroy** [comment]
You probably need to update the dnvm.cmd with this change https://github.com/aspnet/dnvm/commit/c8894c54245d5368b90253ddc8b15db5fe1a9aab

**Comment by markentingh** [comment]
thank you for your help, guys! (I reinstalled Windows again with a different user name already & all is well)

**Comment by muratg** [comment]
:+1:
