### ISSUE TITLE
dnvm install --global does not set global path

### ISSUE THREAD

**Issue by JorritSalverda** [aspnet/dotnetsdk#511]
The runtime is added to the user PATH variable, not to the global one, even though the --global parameter installs the runtime in a globally accessible location. I would expect it to be added to the machine level PATH variable.

**Comment by jonfast565** [comment]
Just installed DNX via DNVM on my organization's web servers, and I have confirmed that the system path is not being written to when using DNVM's 'install/upgrade... -g' option. Only the user path is affected.

**Comment by muratg** [comment]
As we're moving to [dotnet cli](https://dotnet.github.io) in RC2, no more changes in DNVM planned.
