### ISSUE TITLE
Issue with dnvm upgrade

### ISSUE THREAD

**Issue by samarthRT** [aspnet/dotnetsdk#513]
C:\WINDOWS\system32>**dnvm upgrade**
Determining latest version
'dnx-clr-win-x86.1.0.0-rc1-update1' is already installed in C:\Users\firstName LastName.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1.
Adding C:\Users\firstName LastName.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin to process PATH
Adding C:\Users\FirstName LastName.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin to user PATH
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-rc1-update1'
_'C:\Users\firstName'_ is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.

Machine Environment:
VS 2015 Community Edition
DNVM Version : AspNet5.ENU.RC1_Update1_KB3137909.exe
DNX Details : 
C:\WINDOWS\system32>dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16231
 Type:         Clr
 Architecture: x86
 OS Name:      Windows
 OS Version:   10.0
 Runtime Id:   win10-x86

DNVM command script(s):
**C:\Users\firstName LastName\ .dnx\bin**
@Echo off

set DNVM_CMD_PATH_FILE="%USERPROFILE%.dnx\temp-set-envvars.cmd"

PowerShell -NoProfile -NoLogo -ExecutionPolicy unrestricted -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [System.Threading.Thread]::CurrentThread.CurrentUICulture = '';$CmdPathFile='%DNVM_CMD_PATH_FILE%';& '%~dp0dnvm.ps1' %*"

IF EXIST %DNVM_CMD_PATH_FILE% (
  CALL %DNVM_CMD_PATH_FILE%
  DEL %DNVM_CMD_PATH_FILE%
)

**C:\Program Files\Microsoft DNX\Dnvm**
@Echo off

for /f "delims=" %%i in ('PowerShell -NoProfile -NoLogo -ExecutionPolicy unrestricted -Command "[System.IO.Path]::GetTempFileName()"') do set DNVM_CMD_PATH_FILE=%%i.cmd

PowerShell -NoProfile -NoLogo -ExecutionPolicy unrestricted -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [System.Threading.Thread]::CurrentThread.CurrentUICulture = '';$CmdPathFile='%DNVM_CMD_PATH_FILE%';& '%~dp0dnvm.ps1' %*"

IF EXIST %DNVM_CMD_PATH_FILE% (
  CALL %DNVM_CMD_PATH_FILE%
  DEL %DNVM_CMD_PATH_FILE%
)

I've also removed the KRE_Home environment variable. It was >
KRE_HOME
%USERPROFILE%.k

Please suggest.

**Comment by MariovanZeist** [comment]
You probably have a space in your username, and the script might not be able to handle that.

As a workaround you could create the file yourself. Ceate the file `%USERPROFILE%\.dnx\alias\default.txt` which contains `dnx-clr-win-x86.1.0.0-rc1-update1` 

You can verify if that worked by typing `dnvm list`. It should list all the installed sdk's and will show default in the alias column

**Comment by BrennanConroy** [comment]
Real workaround is https://github.com/aspnet/dnvm/issues/510
