### ISSUE TITLE
Is DNVM still in use with .NET Core RTM?

### ISSUE THREAD

**Issue by hiredgunhouse** [aspnet/dotnetsdk#519]
If DNVM is no longer part of .NET Core RTM it would be a good idea to put a comment in the README.md that this repo is for historical purposes only and DNVM is no longer used in .NET Core.

**Comment by muratg** [comment]
Answer to the title: No :smile: 

We'll go through the repos and do this kind of clean up.

cc @Eilon

**Comment by Eilon** [comment]
Will do!

**Comment by Eilon** [comment]
I updated https://github.com/aspnet/dnx and https://github.com/aspnet/dnvm to reflect that they are obsolete.
