### ISSUE TITLE
dnvm update-self exception and 404 Not Found

### ISSUE THREAD

**Issue by HolyHorseman** [aspnet/dotnetsdk#520]
Dear all,
Sometime ago I updated .NET Core SDK to version 1.1.0(preview2-1-003177). When I run "dnvm update-self" in command prompt as administrator today, the result shown: 
![image](https://cloud.githubusercontent.com/assets/12827492/21672249/2d3d6324-d35c-11e6-9355-9e3a60fb04d8.png)

However, it is work well before updated. Does anybody know how to fix it? 
Now my environment is as below: 
1. Windows 10.0.10586
2. Microsoft .NET Core Shared Framework Host
Version  : 1.1.0
Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
3. .NET Version Manager v1.0.0-rc2-15546
Current feed settings:
Default Stable: https://www.nuget.org/api/v2
Default Unstable: https://www.myget.org/F/aspnetvnext/api/v2
Current Stable Override: <none>
Current Unstable Override: <none>

Thanks, all.

**Comment by BrennanConroy** [comment]
DNVM isn't used anymore, it was for handling `dnx` versions, you are using `dotnet` now

**Comment by HolyHorseman** [comment]
Thank you, @BrennanConroy.
After updated .NET Core 1.0.0, I had used `dotnet`, but `dnvm` also was used at that time. So this caused me the question. I am clear now.

On the other hand, how to update .NET Core version? I can't find out a `dotnet` command. 
In fact I like using `dnvm` to manage version. Now I only download directly from website.        ╮(╯-╰)╭
