### ISSUE TITLE
Can not download DNVM anymore

### ISSUE THREAD

**Issue by andras-aniski** [aspnet/dotnetsdk#521]
I know that **DNVM** is obsoleted, but **dotnet** does not support Unix-based systems (Debian) with **ARM architecture** yet.
We are (we were) using DNVM on hundreds of devices over the country, and we would still need it until dotnet is not in usable phase - for us. 

We were using the command on Debian to download DNVM:
`curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source  ~/.dnx/dnvm/dnvm.sh`

Now it returns with 404 not found.

Could someone please suggest us solutions, how can we install DNVM on our IoT devices (Debian on ARM), and our developer PCs (Windows)?

Thanks!

**Comment by glennc** [comment]
If you really need DNVM for migration purposes then you should grab it from either a commit specific link on the Home repo or here, changing the URL to whichever you need.
