### ISSUE TITLE
kvm upgrade with Dev feed fails

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/dotnetsdk#95]
Trying to run:

    kvm uprade

with the dev feed fails with:

    c:\>kvm upgrade
    Determining latest version
    Exception calling "DownloadString" with "1" argument(s): "The remote server returned an err
    or: (400) Bad Request."

Would expect latest version to install.

Also get this when I try to install a version that is not available - I would expect a better error message here that says invalid version.

**Comment by Praburaj** [comment]
@RickStrahl I'm unable to reproduce this issue. What's the version of `kvm` you have? 

I observe the server typically returns a `404` for a non-existing package resulting in a `404` error message from powershell. 400 bad request is being thrown for an incorrect query. For example if the query parameters for version or packgeids missing a single quote (`%27`) around it throws a bad request. Could you check if you contain the latest `kvm` and your `%userprofile%\.kre\bin\kvm.ps1` contains these escape characters? 

```
https://github.com/aspnet/kvm/blob/dev/src/kvm.ps1#L194
```

```
Valid 404 request: 
https://www.myget.org/f/aspnetvnext/api/v2/GetUpdates()?packageIds='KRE-CLR-x86'&versions='2.0.0.rc1'&includePrerelease=true&includeAllVersions=false

400 Bad request:
https://www.myget.org/f/aspnetvnext/api/v2/GetUpdates()?packageIds=KRE-CLR-x86&versions=2.0.0.rc1&includePrerelease=true&includeAllVersions=false

```

**Comment by RickStrahl** [comment]
This resolved with later builds
